export const GET_PRODUCT_DATA_REQUEST = 'GET_PRODUCT_DATA_REQUEST';
export const GET_PRODUCT_DATA_SUCCESS = 'GET_PRODUCT_DATA_SUCCESS';
export const GET_PRODUCT_DATA_FAILURE = 'GET_PRODUCT_DATA_FAILURE';

export const POST_PRODUCT_DATA_REQUEST = 'POST_PRODUCT_DATA_REQUEST';
export const POST_PRODUCT_DATA_SUCCESS = 'POST_PRODUCT_DATA_SUCCESS';
export const POST_PRODUCT_DATA_FAILURE = 'POST_PRODUCT_DATA_FAILURE';